---
name: "⭕ Trunk"
on:
  push:
    branches: ["main"]
    tags: ["v*.*.*"]
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch: {}

jobs:
  check-call:
    name: "⚡"
    uses: z-shell/.github/.github/workflows/trunk.yml@main
    with:
      arguments: --no-progress
